/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package tappchart

import com.tapptitude.tappchart.Library
import kotlin.test.Test
import kotlin.test.assertTrue

class LibraryTest {
    @Test fun someLibraryMethodReturnsTrue() {
        val classUnderTest = Library()
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }
}
